---

# Parameter file for running hodpy and HOD_Mock_Pipeline
# Contains the paths to the relevant folders and such for SOAP, snapshots, etc.
# Also includes N and L for convenience

Paths:
  soap_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/DMO_FIDUCIAL/SOAP/halo_properties_0077.hdf5
  snapshot_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/DMO_FIDUCIAL/snapshots/flamingo_0077/flamingo_0077.hdf5 # should be a single file
  lightcone_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/DMO_FIDUCIAL/lightcones/lightcone0_particles/
  params_path: /cosma8/data/dp004/flamingo/Runs/L1000N1800/DMO_FIDUCIAL/used_parameters.yml

Params:
  #these might need to be changed
  N: 1800
  L: 1000
  redshift: 0.0
  photsys: "S"
  #these probably don't need to be changed
  mag_faint: -18
  log_mass_min: -11
  logMmin: 10.3 # Minimum mass of unresolved halo tracers for BGS or what have you
  logMmax: 11 # Maximum mass of unresolved halo tracers; SHOULD BE CHANGED FOR FLAMINGO
  ntracer: 3 # Number of satellite tracers for each halo
  particles: False # use particles to position galaxy tracers if True, NFW if False; True not yet supported with Flamingo

Misc:
  random_seed: 1